version: '3.8'

services:
  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-p", "4222", "-m", "8222", "--store", "file", "--dir", "/data", "--max_age", "72h"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: .
    volumes:
      - .:/app
    environment:
      - NATS_URL=nats://nats-streaming:4222
      - NATS_SUBJECT=orders
      - REDIS_URL=redis://redis:6379
    depends_on:
      - nats-streaming
      - redis
