version: '3.8'

services:
  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-p", "4222", "-m", "8222", "--store", "file", "--dir", "/data", "--max_age", "72h"]

  app:
    build: .
    volumes:
      - .:/app
    environment:
      - NATS_URL=nats://nats-streaming:4222
      - NATS_SUBJECT=orders
    depends_on:
      - nats-streaming
