// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrderDataColumns holds the columns for the "order_data" table.
	OrderDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_uid", Type: field.TypeString},
		{Name: "track_number", Type: field.TypeString},
		{Name: "entry", Type: field.TypeString},
		{Name: "delivery", Type: field.TypeJSON},
		{Name: "payment", Type: field.TypeJSON},
		{Name: "items", Type: field.TypeJSON},
		{Name: "locale", Type: field.TypeString},
		{Name: "internal_signature", Type: field.TypeString},
		{Name: "customer_id", Type: field.TypeString},
		{Name: "delivery_service", Type: field.TypeString},
		{Name: "shardkey", Type: field.TypeString},
		{Name: "sm_id", Type: field.TypeInt},
		{Name: "date_created", Type: field.TypeString},
		{Name: "oof_shard", Type: field.TypeString},
	}
	// OrderDataTable holds the schema information for the "order_data" table.
	OrderDataTable = &schema.Table{
		Name:       "order_data",
		Columns:    OrderDataColumns,
		PrimaryKey: []*schema.Column{OrderDataColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrderDataTable,
	}
)

func init() {
}
