// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nats-streaming-web/ent/orderdata"
	"nats-streaming-web/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderDataDelete is the builder for deleting a OrderData entity.
type OrderDataDelete struct {
	config
	hooks    []Hook
	mutation *OrderDataMutation
}

// Where appends a list predicates to the OrderDataDelete builder.
func (odd *OrderDataDelete) Where(ps ...predicate.OrderData) *OrderDataDelete {
	odd.mutation.Where(ps...)
	return odd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (odd *OrderDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, odd.sqlExec, odd.mutation, odd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (odd *OrderDataDelete) ExecX(ctx context.Context) int {
	n, err := odd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (odd *OrderDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderdata.Table, sqlgraph.NewFieldSpec(orderdata.FieldID, field.TypeInt))
	if ps := odd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, odd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	odd.mutation.done = true
	return affected, err
}

// OrderDataDeleteOne is the builder for deleting a single OrderData entity.
type OrderDataDeleteOne struct {
	odd *OrderDataDelete
}

// Where appends a list predicates to the OrderDataDelete builder.
func (oddo *OrderDataDeleteOne) Where(ps ...predicate.OrderData) *OrderDataDeleteOne {
	oddo.odd.mutation.Where(ps...)
	return oddo
}

// Exec executes the deletion query.
func (oddo *OrderDataDeleteOne) Exec(ctx context.Context) error {
	n, err := oddo.odd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderdata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oddo *OrderDataDeleteOne) ExecX(ctx context.Context) {
	if err := oddo.Exec(ctx); err != nil {
		panic(err)
	}
}
