// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"nats-streaming-web/ent/orderdata"
	"nats-streaming-web/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderDataQuery is the builder for querying OrderData entities.
type OrderDataQuery struct {
	config
	ctx        *QueryContext
	order      []orderdata.OrderOption
	inters     []Interceptor
	predicates []predicate.OrderData
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderDataQuery builder.
func (odq *OrderDataQuery) Where(ps ...predicate.OrderData) *OrderDataQuery {
	odq.predicates = append(odq.predicates, ps...)
	return odq
}

// Limit the number of records to be returned by this query.
func (odq *OrderDataQuery) Limit(limit int) *OrderDataQuery {
	odq.ctx.Limit = &limit
	return odq
}

// Offset to start from.
func (odq *OrderDataQuery) Offset(offset int) *OrderDataQuery {
	odq.ctx.Offset = &offset
	return odq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (odq *OrderDataQuery) Unique(unique bool) *OrderDataQuery {
	odq.ctx.Unique = &unique
	return odq
}

// Order specifies how the records should be ordered.
func (odq *OrderDataQuery) Order(o ...orderdata.OrderOption) *OrderDataQuery {
	odq.order = append(odq.order, o...)
	return odq
}

// First returns the first OrderData entity from the query.
// Returns a *NotFoundError when no OrderData was found.
func (odq *OrderDataQuery) First(ctx context.Context) (*OrderData, error) {
	nodes, err := odq.Limit(1).All(setContextOp(ctx, odq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orderdata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (odq *OrderDataQuery) FirstX(ctx context.Context) *OrderData {
	node, err := odq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderData ID from the query.
// Returns a *NotFoundError when no OrderData ID was found.
func (odq *OrderDataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = odq.Limit(1).IDs(setContextOp(ctx, odq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orderdata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (odq *OrderDataQuery) FirstIDX(ctx context.Context) int {
	id, err := odq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderData entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderData entity is found.
// Returns a *NotFoundError when no OrderData entities are found.
func (odq *OrderDataQuery) Only(ctx context.Context) (*OrderData, error) {
	nodes, err := odq.Limit(2).All(setContextOp(ctx, odq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orderdata.Label}
	default:
		return nil, &NotSingularError{orderdata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (odq *OrderDataQuery) OnlyX(ctx context.Context) *OrderData {
	node, err := odq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderData ID in the query.
// Returns a *NotSingularError when more than one OrderData ID is found.
// Returns a *NotFoundError when no entities are found.
func (odq *OrderDataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = odq.Limit(2).IDs(setContextOp(ctx, odq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orderdata.Label}
	default:
		err = &NotSingularError{orderdata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (odq *OrderDataQuery) OnlyIDX(ctx context.Context) int {
	id, err := odq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderDataSlice.
func (odq *OrderDataQuery) All(ctx context.Context) ([]*OrderData, error) {
	ctx = setContextOp(ctx, odq.ctx, "All")
	if err := odq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrderData, *OrderDataQuery]()
	return withInterceptors[[]*OrderData](ctx, odq, qr, odq.inters)
}

// AllX is like All, but panics if an error occurs.
func (odq *OrderDataQuery) AllX(ctx context.Context) []*OrderData {
	nodes, err := odq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderData IDs.
func (odq *OrderDataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if odq.ctx.Unique == nil && odq.path != nil {
		odq.Unique(true)
	}
	ctx = setContextOp(ctx, odq.ctx, "IDs")
	if err = odq.Select(orderdata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (odq *OrderDataQuery) IDsX(ctx context.Context) []int {
	ids, err := odq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (odq *OrderDataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, odq.ctx, "Count")
	if err := odq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, odq, querierCount[*OrderDataQuery](), odq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (odq *OrderDataQuery) CountX(ctx context.Context) int {
	count, err := odq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (odq *OrderDataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, odq.ctx, "Exist")
	switch _, err := odq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (odq *OrderDataQuery) ExistX(ctx context.Context) bool {
	exist, err := odq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderDataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (odq *OrderDataQuery) Clone() *OrderDataQuery {
	if odq == nil {
		return nil
	}
	return &OrderDataQuery{
		config:     odq.config,
		ctx:        odq.ctx.Clone(),
		order:      append([]orderdata.OrderOption{}, odq.order...),
		inters:     append([]Interceptor{}, odq.inters...),
		predicates: append([]predicate.OrderData{}, odq.predicates...),
		// clone intermediate query.
		sql:  odq.sql.Clone(),
		path: odq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrderUID string `json:"order_uid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderData.Query().
//		GroupBy(orderdata.FieldOrderUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (odq *OrderDataQuery) GroupBy(field string, fields ...string) *OrderDataGroupBy {
	odq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderDataGroupBy{build: odq}
	grbuild.flds = &odq.ctx.Fields
	grbuild.label = orderdata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrderUID string `json:"order_uid,omitempty"`
//	}
//
//	client.OrderData.Query().
//		Select(orderdata.FieldOrderUID).
//		Scan(ctx, &v)
func (odq *OrderDataQuery) Select(fields ...string) *OrderDataSelect {
	odq.ctx.Fields = append(odq.ctx.Fields, fields...)
	sbuild := &OrderDataSelect{OrderDataQuery: odq}
	sbuild.label = orderdata.Label
	sbuild.flds, sbuild.scan = &odq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderDataSelect configured with the given aggregations.
func (odq *OrderDataQuery) Aggregate(fns ...AggregateFunc) *OrderDataSelect {
	return odq.Select().Aggregate(fns...)
}

func (odq *OrderDataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range odq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, odq); err != nil {
				return err
			}
		}
	}
	for _, f := range odq.ctx.Fields {
		if !orderdata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if odq.path != nil {
		prev, err := odq.path(ctx)
		if err != nil {
			return err
		}
		odq.sql = prev
	}
	return nil
}

func (odq *OrderDataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderData, error) {
	var (
		nodes = []*OrderData{}
		_spec = odq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrderData).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrderData{config: odq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, odq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (odq *OrderDataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := odq.querySpec()
	_spec.Node.Columns = odq.ctx.Fields
	if len(odq.ctx.Fields) > 0 {
		_spec.Unique = odq.ctx.Unique != nil && *odq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, odq.driver, _spec)
}

func (odq *OrderDataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orderdata.Table, orderdata.Columns, sqlgraph.NewFieldSpec(orderdata.FieldID, field.TypeInt))
	_spec.From = odq.sql
	if unique := odq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if odq.path != nil {
		_spec.Unique = true
	}
	if fields := odq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderdata.FieldID)
		for i := range fields {
			if fields[i] != orderdata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := odq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := odq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := odq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := odq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (odq *OrderDataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(odq.driver.Dialect())
	t1 := builder.Table(orderdata.Table)
	columns := odq.ctx.Fields
	if len(columns) == 0 {
		columns = orderdata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if odq.sql != nil {
		selector = odq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if odq.ctx.Unique != nil && *odq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range odq.predicates {
		p(selector)
	}
	for _, p := range odq.order {
		p(selector)
	}
	if offset := odq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := odq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderDataGroupBy is the group-by builder for OrderData entities.
type OrderDataGroupBy struct {
	selector
	build *OrderDataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (odgb *OrderDataGroupBy) Aggregate(fns ...AggregateFunc) *OrderDataGroupBy {
	odgb.fns = append(odgb.fns, fns...)
	return odgb
}

// Scan applies the selector query and scans the result into the given value.
func (odgb *OrderDataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, odgb.build.ctx, "GroupBy")
	if err := odgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderDataQuery, *OrderDataGroupBy](ctx, odgb.build, odgb, odgb.build.inters, v)
}

func (odgb *OrderDataGroupBy) sqlScan(ctx context.Context, root *OrderDataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(odgb.fns))
	for _, fn := range odgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*odgb.flds)+len(odgb.fns))
		for _, f := range *odgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*odgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := odgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderDataSelect is the builder for selecting fields of OrderData entities.
type OrderDataSelect struct {
	*OrderDataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ods *OrderDataSelect) Aggregate(fns ...AggregateFunc) *OrderDataSelect {
	ods.fns = append(ods.fns, fns...)
	return ods
}

// Scan applies the selector query and scans the result into the given value.
func (ods *OrderDataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ods.ctx, "Select")
	if err := ods.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderDataQuery, *OrderDataSelect](ctx, ods.OrderDataQuery, ods, ods.inters, v)
}

func (ods *OrderDataSelect) sqlScan(ctx context.Context, root *OrderDataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ods.fns))
	for _, fn := range ods.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ods.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ods.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
