// Code generated by ent, DO NOT EDIT.

package ent

import (
	"nats-streaming-web/ent/orderdata"
	"nats-streaming-web/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderdataFields := schema.OrderData{}.Fields()
	_ = orderdataFields
	// orderdataDescOrderUID is the schema descriptor for order_uid field.
	orderdataDescOrderUID := orderdataFields[0].Descriptor()
	// orderdata.OrderUIDValidator is a validator for the "order_uid" field. It is called by the builders before save.
	orderdata.OrderUIDValidator = orderdataDescOrderUID.Validators[0].(func(string) error)
}
